version: '3.3'

services:
  go-api:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    container_name: autotester-go
    ports:
      - "8081:8081"
    environment:
      - TIMEOUT=3
      - PYTHON_API_URL=http://python-api:3000
      - FRONTEND_URL=http://frontend:3001
    volumes:
      - ./logs:/app/logs
    networks:
      - autotester-network
    depends_on:
      - python-api

  python-api:
    build:
      context: ./python
      dockerfile: Dockerfile.py
    container_name: autotester-python
    ports:
      - "3000:3000"
    networks:
      - autotester-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.flutter
    container_name: autotester-frontend
    networks:
      - autotester-network
    command: sh -c "flutter build web && tail -f /dev/null"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/build/web:/usr/share/nginx/html:ro 
    depends_on:
      - frontend
      - go-api
    networks:
      - autotester-network

networks:
  autotester-network:
    driver: bridge
